services:
  api:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: ecoruteando-api
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"