// <auto-generated />
using System;
using Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Entity.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("Action");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("NewData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableName")
                        .HasColumnType("integer")
                        .HasColumnName("TableName");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Api.Domain.Entity.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("BackgroundColor")
                        .HasColumnType("integer");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("Api.Domain.Entity.ObstacleReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfileId1")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId1");

                    b.ToTable("ObstacleReports");
                });

            modelBuilder.Entity("Api.Domain.Entity.PasswordRecovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsUsed");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("PasswordRecovery");
                });

            modelBuilder.Entity("Api.Domain.Entity.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PointOfInterest");
                });

            modelBuilder.Entity("Api.Domain.Entity.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfigurationId1")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId")
                        .IsUnique();

                    b.HasIndex("ConfigurationId1");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Api.Domain.Entity.ReportValidation", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("ConfirmationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("ObstacleReportId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfileId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProfileId", "ReportId");

                    b.HasIndex("ObstacleReportId");

                    b.HasIndex("ProfileId1");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportValidation");
                });

            modelBuilder.Entity("Api.Domain.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Api.Domain.Entity.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("Api.Domain.Entity.Route", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Api.Domain.Entity.RouteReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("ProfileId");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("RouteId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteReview");
                });

            modelBuilder.Entity("Api.Domain.Entity.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("Active");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Api.Domain.Entity.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("Priority");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("ProfileId");

                    b.Property<int?>("ProfileId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId1");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Api.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Domain.Entity.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Api.Domain.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Api.Domain.TravelHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfileId1")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int?>("RouteId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId1");

                    b.HasIndex("RouteId");

                    b.HasIndex("RouteId1");

                    b.ToTable("TravelHistories");
                });

            modelBuilder.Entity("Api.Domain.Entity.AuditLog", b =>
                {
                    b.HasOne("Api.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.User", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId1");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.IpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<int>("AuditLogId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("IpAddress");

                            b1.HasKey("AuditLogId");

                            b1.ToTable("AuditLog");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogId");
                        });

                    b.Navigation("IpAddress")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entity.ObstacleReport", b =>
                {
                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Profile", null)
                        .WithMany("ObstacleReport")
                        .HasForeignKey("ProfileId1");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("ObstacleReportId")
                                .HasColumnType("integer");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("ObstacleReportId");

                            b1.ToTable("ObstacleReports");

                            b1.WithOwner()
                                .HasForeignKey("ObstacleReportId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.UrlImagen", "PhotoUrl", b1 =>
                        {
                            b1.Property<int>("ObstacleReportId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ObstacleReportId");

                            b1.ToTable("ObstacleReports");

                            b1.WithOwner()
                                .HasForeignKey("ObstacleReportId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PhotoUrl")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Api.Domain.Entity.PasswordRecovery", b =>
                {
                    b.HasOne("Api.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.User", null)
                        .WithMany("PasswordRecovery")
                        .HasForeignKey("UserId1");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.ExpirationDate", "ExpirationDate", b1 =>
                        {
                            b1.Property<int>("PasswordRecoveryId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ExpirationDate");

                            b1.HasKey("PasswordRecoveryId");

                            b1.ToTable("PasswordRecovery");

                            b1.WithOwner()
                                .HasForeignKey("PasswordRecoveryId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.RecoveryCode", "TemporaryCode", b1 =>
                        {
                            b1.Property<int>("PasswordRecoveryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RecoveryCode");

                            b1.HasKey("PasswordRecoveryId");

                            b1.ToTable("PasswordRecovery");

                            b1.WithOwner()
                                .HasForeignKey("PasswordRecoveryId");
                        });

                    b.Navigation("ExpirationDate")
                        .IsRequired();

                    b.Navigation("TemporaryCode")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entity.PointOfInterest", b =>
                {
                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Profile", null)
                        .WithMany("PointOfInterest")
                        .HasForeignKey("ProfileId");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("PointOfInterestId")
                                .HasColumnType("integer");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("PointOfInterestId");

                            b1.ToTable("PointOfInterest");

                            b1.WithOwner()
                                .HasForeignKey("PointOfInterestId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.PlaceName", "Name", b1 =>
                        {
                            b1.Property<int>("PointOfInterestId")
                                .HasColumnType("integer");

                            b1.HasKey("PointOfInterestId");

                            b1.ToTable("PointOfInterest");

                            b1.WithOwner()
                                .HasForeignKey("PointOfInterestId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Api.Domain.Entity.Profile", b =>
                {
                    b.HasOne("Api.Domain.Entity.Configuration", "Configuration")
                        .WithOne()
                        .HasForeignKey("Api.Domain.Entity.Profile", "ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Configuration", null)
                        .WithMany("Profile")
                        .HasForeignKey("ConfigurationId1");

                    b.HasOne("Api.Domain.Entity.Session", "Session")
                        .WithOne()
                        .HasForeignKey("Api.Domain.Entity.Profile", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.UrlImagen", "ProfilePicture", b1 =>
                        {
                            b1.Property<int>("ProfileId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("ProfileId")
                                .HasColumnType("integer");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Configuration");

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("ProfilePicture")
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Api.Domain.Entity.ReportValidation", b =>
                {
                    b.HasOne("Api.Domain.Entity.ObstacleReport", null)
                        .WithMany("ReportValidation")
                        .HasForeignKey("ObstacleReportId");

                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Profile", null)
                        .WithMany("ReportValidation")
                        .HasForeignKey("ProfileId1");

                    b.HasOne("Api.Domain.Entity.ObstacleReport", "ObstacleReport")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObstacleReport");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Api.Domain.Entity.RolePermission", b =>
                {
                    b.HasOne("Api.Domain.Permission", "Permission")
                        .WithMany("RolePermission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Role", "Role")
                        .WithMany("RolePermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.Domain.Entity.Route", b =>
                {
                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Profile", null)
                        .WithMany("Routes")
                        .HasForeignKey("ProfileId");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.Distance", "DistanceKm", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("DistanceKm");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.RouteName", "Name", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.RoutePath", "Path", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<string>("SerializedPoints")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Points");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.TimeValue", "EstimatedTime", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("EstimatedTime");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("DistanceKm")
                        .IsRequired();

                    b.Navigation("EstimatedTime")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Path")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Api.Domain.Entity.RouteReview", b =>
                {
                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Api.Domain.Entity.Session", b =>
                {
                    b.HasOne("Api.Domain.Entity.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.IpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<int>("SessionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("IpAddress");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.SessionEndDate", "EndDate", b1 =>
                        {
                            b1.Property<int>("SessionId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndDate");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("EndDate")
                        .IsRequired();

                    b.Navigation("IpAddress")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entity.SupportTicket", b =>
                {
                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Profile", null)
                        .WithMany("SupportTickets")
                        .HasForeignKey("ProfileId1");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.TicketSubject", "Subject", b1 =>
                        {
                            b1.Property<int>("SupportTicketId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Subject");

                            b1.HasKey("SupportTicketId");

                            b1.ToTable("SupportTickets");

                            b1.WithOwner()
                                .HasForeignKey("SupportTicketId");
                        });

                    b.Navigation("Profile");

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.Entity.User", b =>
                {
                    b.OwnsOne("Api.Domain.Entity.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.Username", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.Entity.UserRole", b =>
                {
                    b.HasOne("Api.Domain.Entity.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Permission", b =>
                {
                    b.OwnsOne("Api.Domain.Entity.ValueObjects.PermissionName", "Name", b1 =>
                        {
                            b1.Property<int>("PermissionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("PermissionId");

                            b1.ToTable("Permission");

                            b1.WithOwner()
                                .HasForeignKey("PermissionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.TravelHistory", b =>
                {
                    b.HasOne("Api.Domain.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Profile", null)
                        .WithMany("TravelHistory")
                        .HasForeignKey("ProfileId1");

                    b.HasOne("Api.Domain.Entity.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entity.Route", null)
                        .WithMany("TravelHistory")
                        .HasForeignKey("RouteId1");

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.CO2", "CO2SavedKg", b1 =>
                        {
                            b1.Property<int>("TravelHistoryId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("CO2SavedKg");

                            b1.HasKey("TravelHistoryId");

                            b1.ToTable("TravelHistories");

                            b1.WithOwner()
                                .HasForeignKey("TravelHistoryId");
                        });

                    b.OwnsOne("Api.Domain.Entity.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<int>("TravelHistoryId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndTime");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartTime");

                            b1.HasKey("TravelHistoryId");

                            b1.ToTable("TravelHistories");

                            b1.WithOwner()
                                .HasForeignKey("TravelHistoryId");
                        });

                    b.Navigation("CO2SavedKg")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Route");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.Entity.Configuration", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Api.Domain.Entity.ObstacleReport", b =>
                {
                    b.Navigation("ReportValidation");
                });

            modelBuilder.Entity("Api.Domain.Entity.Profile", b =>
                {
                    b.Navigation("ObstacleReport");

                    b.Navigation("PointOfInterest");

                    b.Navigation("ReportValidation");

                    b.Navigation("Routes");

                    b.Navigation("SupportTickets");

                    b.Navigation("TravelHistory");
                });

            modelBuilder.Entity("Api.Domain.Entity.Role", b =>
                {
                    b.Navigation("RolePermission");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Api.Domain.Entity.Route", b =>
                {
                    b.Navigation("TravelHistory");
                });

            modelBuilder.Entity("Api.Domain.Entity.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PasswordRecovery");

                    b.Navigation("Sessions");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Api.Domain.Permission", b =>
                {
                    b.Navigation("RolePermission");
                });
#pragma warning restore 612, 618
        }
    }
}
